### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'GBM39_AR_output/GBM39_test/GBM39/reconstructions/GBM39_paths_cycles.txt'

### ISSUE THREAD

**Issue by THZ34** [jluebeck/AmpliconReconstructor#1]
This error has happened in AR test，what the 'GBM39_paths_cycles.txt' file is?

**Comment by jluebeck** [comment]
Hi, THZ34 - I am unable to recreate the issue you are experiencing. Would you be able to share the command you are running that generates this issue?

I tweaked the documentation to make the demo easier to follow. Please, let me know if the issue persists.
