### ISSUE TITLE
OMPathFinder runs more than 1 h and stoped due to run out of memory

### ISSUE THREAD

**Issue by lxiong1992** [jluebeck/AmpliconReconstructor#6]
Hello AmpliconReconstructorOM developer,

I am recently running AmpliconReconstructorOM and the log report showing that everything is normal, but at the stage of OMPathFinder, it runs extremely long at the step of finding all non-extendible paths (>1h) and failed when the memory was used up. I run the softwares in a 256G memory linux server. This is already a huge memory I think. 

When I test a small amplicon with few segments, it works totally fine. It has the problem only when I use a big amplicon with ~50 segments. In the output alignment folder, there are ~350 *_aln.txt alignments files. I guess probably the large number of segments + contigs cause some problem?

Is there a way I can solve this issue? 

Thanks,

Le

**Comment by lxiong1992** [comment]
An update:

When I use --noConnect option, I can run it and I got 40 cycle plots in visualizations folder.

**Comment by jluebeck** [comment]
Hi Le,

Thank you for this message - it seems that for very large and complex amplicons the method has limitations. I suggest the following steps help in cases like this:
1. Run with `--noConnect`
2. In the outputs, identify contigs which have meaningful structural variants captured in the amplified regions.
3. Specify `--contig_subset` followed by the list of contig IDs that are relevant to your reconstruction and run again without `--noConnect`. This way the set of candidate paths should be more tractable.

In some extremely complex and heterogeneous cases, there are limitations imposed by the assembly of the OM contigs themselves and the true collection of structures present may not be discernable with this method.

Thanks,
Jens

**Comment by lxiong1992** [comment]
Hi Jens,

OK, thanks for you suggestions. I will try.

Best,
Le
